# Generated by Django 4.0.3 on 2022-03-02 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_preview',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
