# Generated by Django 4.0.3 on 2022-03-02 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_content_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content_preview',
            field=models.CharField(default='default', editable=False, max_length=300),
            preserve_default=False,
        ),
    ]
